### ISSUE TITLE
Question about differential analysis

### ISSUE THREAD

**Issue by re2srm** [shawnzhangyx/PePr#35]
Hello,

I am a little unsure about how the differential analysis works using the --diff tag. I want to compare binding of my protein in two different conditions (wildtype and ko) each of which has its own input control.  Here is my code:

PePr --chip1 KO1.bam,KO2.bam --chip2 WT1.bam,WT2.bam --input1 InputKO.bam --input2 InputWT.bam -f bampe --diff --threshold 0.01 

This gives me two peak files called chip1 and chip2. Do these two files represent the peaks enriched in each condition relative to its control? Or do these files represent peaks enriched in each condition relative to the other condition while normalizing against the relevant control (i.e KO/inputKO vs WT/inputWT and WT/inputWT vs KO/inputKO )? What what be the result if I run the same command without the -diff tag?

It would be great if you can clarify this.

Thanks

**Comment by shawnzhangyx** [comment]
Hi, 

Sorry for the late reply... If you add a diff tag, the chip1 and chip2 output peak files will be peaks that are enriched in each condition against the other condition while normalizing against their own input. This will not give you all the peaks present in that condition.  

If you suspect there are major differences between the peaks in the KO, I would recommend using a intra-group normalization, otherwise the result will be strange. 

If no -diff tag is given, I think it will simply give you the peaks in the chip1 compared to input1, without looking at chip2. If you want to obtain the peaks in each condition, you could run PePr with the single-condition mode. 

I hope it clarifies something. Let me know if you have additional quesitons. 

Best,
Yanxiao

**Comment by re2srm** [comment]
Thanks a lot. It is clear now.
