### ISSUE TITLE
add support for paired-end reads

### ISSUE THREAD

**Issue by shawnzhangyx** [shawnzhangyx/PePr#8]

**Comment by mictadlo** [comment]
Maybe in the same way how JAMM does it https://github.com/mahmoudibrahim/JAMM

**Comment by shawnzhangyx** [comment]
Thanks very much for letting me know, Michal! I'll look into it.

**Comment by mictadlo** [comment]
Hi,
HiChip paper ( http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-15-280 ) describes how they added paired-end support to Sicer:

_For paired-end reads, the HiChIP pipeline keeps the first end and extends by the fragment length estimated from mapping positions of the two ends, rather than by the average fragment length of the library. Given the variability of fragment lengths across a complex genome like human genome, the use of actual coordinates of mapped pairs is expected to achieve better resolution in signal visualization. The bed file is then used to generate a bedGraph file by the genomeCoverageBed command from BEDTools._

Best wishes,

Michal

**Comment by shawnzhangyx** [comment]
Added support for paired-end reads in release v1.1.8 and later. Only fragments with two ends mapped will be considered. The center of each fragment (by shifting one end by half actual fragment length) will be input to the next stage (statistical testings).
